block_labels = [ "DO NOT MERGE" ]

status = [
    "codecov/patch",
    # "codecov/project",
    "continuous-integration/travis-ci/push",
]

timeout_sec = 576000

[committer]
name = "BCBI Bot"
email = "bcbi-git@brown.edu"
