block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

status = [
    "CI (1, x64, macos-latest)",
    "CI (1, x64, ubuntu-latest)",
    "CI (nightly, x64, macos-latest)",
    "CI (nightly, x64, ubuntu-latest)",
    "Compatibility",
    "Docs",
    "VersionVigilante",
    # "codecov/patch",
    # "codecov/project",
]

timeout_sec = 36000

[committer]
name = "BCBI Bot"
email = "bcbi-git@brown.edu"
