##### Beginning of file

# This file was generated by PredictMD version 0.20.0-DEV
# For help, please visit https://www.predictmd.net

import PredictMD

### Begin project-specific settings

PredictMD.require_julia_version("v0.7.0")

PredictMD.require_predictmd_version("0.20.0-DEV")

# PredictMD.require_predictmd_version("0.20.0-DEV", "0.21.0-")

PROJECT_OUTPUT_DIRECTORY = PredictMD.project_directory(
    homedir(),
    "Desktop",
    "breast_cancer_biopsy_example",
    )

### End project-specific settings

### Begin model comparison code

display(prplottesting)

### End model comparison code

##### End of file

# This file was generated using Literate.jl, https://github.com/fredrikekre/Literate.jl

