site_name: PredictMD.jl
# repo_url: https://github.com/bcbi/PredictMD.jl
site_description: Uniform interface for machine learning in Julia
site_author: Center for Biomedical Informatics, Brown University

theme: readthedocs

extra_css:
    - assets/Documenter.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js

markdown_extensions:
    - extra
    - fenced_code
    - mdx_math
    - tables

docs_dir: 'build'

pages:
    - 'Home': 'index.md'
    - 'Requirements for plotting (optional)': 'requirements_for_plotting.md'
    - 'Examples':
        - 'Boston housing (single label regression)':
            - '1. Preprocess data': 'examples/cpu/boston_housing/01_preprocess_data.md'
            - '2. Linear regression': 'examples/cpu/boston_housing/02_linear_regression.md'
            - '3. Random forest regression': 'examples/cpu/boston_housing/03_random_forest_regression.md'
            - '4. Knet neural network regression': 'examples/cpu/boston_housing/04_knet_mlp_regression.md'
            - '5. Compare models': 'examples/cpu/boston_housing/05_compare_models.md'
            - '6. Directly access model output': 'examples/cpu/boston_housing/06_get_model_output.md'
        - 'Breast cancer biopsy (single label binary classification)':
            - '1. Preprocess data': 'examples/cpu/breast_cancer_biopsy/01_preprocess_data.md'
            - '2. Apply SMOTE algorithm': 'examples/cpu/breast_cancer_biopsy/02_smote.md'
            - '3. Logistic classifier': 'examples/cpu/breast_cancer_biopsy/03_logistic_classifier.md'
            - '4. Random forest classifier': 'examples/cpu/breast_cancer_biopsy/04_random_forest_classifier.md'
            - '5. C-SVC support vector machine classifier': 'examples/cpu/breast_cancer_biopsy/05_c_svc_svm_classifier.md'
            - '6. nu-SVC support vector machine classifier': 'examples/cpu/breast_cancer_biopsy/06_nu_svc_svm_classifier.md'
            - '7. Knet neural network classifier': 'examples/cpu/breast_cancer_biopsy/07_knet_mlp_classifier.md'
            - '8. Compare models': 'examples/cpu/breast_cancer_biopsy/08_compare_models.md'
            - '9. Directly access model output': 'examples/cpu/breast_cancer_biopsy/09_get_model_output.md'
    - 'Library':
        - 'Internals': 'library/internals.md'
