include("preprocessing/dataframecontrasts.jl")
include("preprocessing/dataframetodecisiontree.jl")
include("preprocessing/dataframetoglm.jl")
include("preprocessing/dataframetoknet.jl")
include("preprocessing/dataframetosvm.jl")
