include("preprocessing/dataframe2decisiontree.jl")
include("preprocessing/dataframe2glm.jl")
include("preprocessing/dataframe2knet.jl")
include("preprocessing/dataframe2svm.jl")
include("preprocessing/dataframecontrasts.jl")
