include("utils/formulas.jl")
include("utils/labelstringintmaps.jl")
include("utils/openbrowserwindow.jl")
include("utils/shufflerows.jl")
include("utils/tikzpictures.jl")
include("utils/trapz.jl")
include("utils/travisci.jl")
